### **Training**

In [1]:
import pandas as pd
training_data = pd.read_csv('hm_hospitales_covid_structured_30d_train.csv')
training_output = pd.read_csv('split_train_export_30d.csv')

## check input data size
training_data.shape[0]
## 1834
training_data.shape[1]
## 48

# training_data.isnull().sum()
# training_data.dtypes
 
## split date and time
# training_data[['date','time']] = training_data['admission_datetime'].str.split(" ", 1, expand=True)
training_data = training_data.drop(['admission_datetime'], axis=1)

## convert string into category
training_data = training_data.replace('MALE', 1) 
training_data = training_data.replace('FEMALE', 0)

## convert string into category
training_data = training_data.replace('sx_breathing_difficulty', 1) 
training_data = training_data.replace('sx_others', 2) 
training_data = training_data.replace('sx_flu', 3) 
training_data = training_data.replace('sx_fever', 4) 
training_data = training_data.replace('sx_cough', 5)

**Pre-processing** <br>
Missing data
* Numerical: median
* Categorical: most frequent

In [2]:
## add missing data
training_data.vitals_temp_ed_first = training_data.vitals_temp_ed_first.fillna(training_data['vitals_temp_ed_first'].median())
training_data.vitals_sbp_ed_first = training_data.vitals_sbp_ed_first.fillna(training_data['vitals_sbp_ed_first'].median())
training_data.vitals_dbp_ed_first = training_data.vitals_dbp_ed_first.fillna(training_data['vitals_dbp_ed_first'].median())
training_data.vitals_hr_ed_first = training_data.vitals_hr_ed_first.fillna(training_data['vitals_hr_ed_first'].median())
training_data.vitals_spo2_ed_first = training_data.vitals_spo2_ed_first.fillna(training_data['vitals_spo2_ed_first'].median())
training_data.pmhx_diabetes = training_data.pmhx_diabetes.fillna(training_data['pmhx_diabetes'].mode()[0])
training_data.pmhx_hld = training_data.pmhx_hld.fillna(training_data['pmhx_hld'].mode()[0])
training_data.pmhx_htn = training_data.pmhx_htn.fillna(training_data['pmhx_htn'].mode()[0])
training_data.pmhx_ihd = training_data.pmhx_ihd.fillna(training_data['pmhx_ihd'].mode()[0])
training_data.pmhx_ckd = training_data.pmhx_ckd.fillna(training_data['pmhx_ckd'].mode()[0])
training_data.pmhx_copd = training_data.pmhx_copd.fillna(training_data['pmhx_copd'].mode()[0])
training_data.pmhx_asthma = training_data.pmhx_asthma.fillna(training_data['pmhx_asthma'].mode()[0])
training_data.pmhx_activecancer = training_data.pmhx_activecancer.fillna(training_data['pmhx_activecancer'].mode()[0])
training_data.pmhx_chronicliver = training_data.pmhx_chronicliver.fillna(training_data['pmhx_chronicliver'].mode()[0])
training_data.pmhx_stroke = training_data.pmhx_stroke.fillna(training_data['pmhx_stroke'].mode()[0])
training_data.pmhx_chf = training_data.pmhx_chf.fillna(training_data['pmhx_chf'].mode()[0])
training_data.pmhx_dementia = training_data.pmhx_dementia.fillna(training_data['pmhx_dementia'].mode()[0])
training_data.lab_aptt = training_data.lab_aptt.fillna(training_data['lab_aptt'].median())
training_data.lab_ldh = training_data.lab_ldh.fillna(training_data['lab_ldh'].median())
training_data.lab_sodium = training_data.lab_sodium.fillna(training_data['lab_sodium'].median())
training_data.lab_alt = training_data.lab_alt.fillna(training_data['lab_alt'].median())
training_data.lab_ddimer = training_data.lab_ddimer.fillna(training_data['lab_ddimer'].median())
training_data.lab_glucose = training_data.lab_glucose.fillna(training_data['lab_glucose'].median())
training_data.lab_potassium = training_data.lab_potassium.fillna(training_data['lab_potassium'].median())
training_data.lab_mch = training_data.lab_mch.fillna(training_data['lab_mch'].median())
training_data.lab_mean_platelet_volume = training_data.lab_mean_platelet_volume.fillna(training_data['lab_mean_platelet_volume'].median())
training_data.lab_inr = training_data.lab_inr.fillna(training_data['lab_inr'].median())
training_data.lab_hct = training_data.lab_hct.fillna(training_data['lab_hct'].median())
training_data.lab_creatinine = training_data.lab_creatinine.fillna(training_data['lab_creatinine'].median())
training_data.lab_inr = training_data.lab_inr.fillna(training_data['lab_inr'].median())
training_data.lab_ast = training_data.lab_ast.fillna(training_data['lab_ast'].median())
training_data.lab_crp = training_data.lab_crp.fillna(training_data['lab_crp'].median())
training_data.lab_mcv = training_data.lab_mcv.fillna(training_data['lab_mcv'].median())
training_data.lab_leukocyte = training_data.lab_leukocyte.fillna(training_data['lab_leukocyte'].median())
training_data.lab_lymphocyte_percentage = training_data.lab_lymphocyte_percentage.fillna(training_data['lab_lymphocyte_percentage'].median())
training_data.lab_prothrombin_activity = training_data.lab_prothrombin_activity.fillna(training_data['lab_prothrombin_activity'].median())
training_data.lab_urea = training_data.lab_urea.fillna(training_data['lab_urea'].median())
training_data.lab_rbc = training_data.lab_rbc.fillna(training_data['lab_rbc'].median())
training_data.lab_platelet = training_data.lab_platelet.fillna(training_data['lab_platelet'].median())
training_data.lab_neutrophil = training_data.lab_neutrophil.fillna(training_data['lab_neutrophil'].median())
training_data.lab_neutrophil_percentage = training_data.lab_neutrophil_percentage.fillna(training_data['lab_neutrophil_percentage'].median())
training_data.lab_lymphocyte = training_data.lab_lymphocyte.fillna(training_data['lab_lymphocyte'].median())
training_data.lab_rdw = training_data.lab_rdw.fillna(training_data['lab_rdw'].median())
training_data.lab_hemoglobin = training_data.lab_hemoglobin.fillna(training_data['lab_hemoglobin'].median())

## make sure that there are no missing data
training_data.isnull().sum()

PATIENT ID                   0
age                          0
sex                          0
ed_diagnosis                 0
vitals_temp_ed_first         0
vitals_sbp_ed_first          0
vitals_dbp_ed_first          0
vitals_hr_ed_first           0
vitals_spo2_ed_first         0
pmhx_diabetes                0
pmhx_hld                     0
pmhx_htn                     0
pmhx_ihd                     0
pmhx_ckd                     0
pmhx_copd                    0
pmhx_asthma                  0
pmhx_activecancer            0
pmhx_chronicliver            0
pmhx_stroke                  0
pmhx_chf                     0
pmhx_dementia                0
lab_aptt                     0
lab_ldh                      0
lab_sodium                   0
lab_alt                      0
lab_ddimer                   0
lab_glucose                  0
lab_potassium                0
lab_mch                      0
lab_mean_platelet_volume     0
lab_inr                      0
lab_hct                      0
lab_creatinine               0
lab_ast                      0
lab_crp                      0
lab_mcv                      0
lab_leukocyte                0
lab_lymphocyte_percentage    0
lab_prothrombin_activity     0
lab_urea                     0
lab_rbc                      0
lab_platelet                 0
lab_neutrophil               0
lab_neutrophil_percentage    0
lab_lymphocyte               0
lab_rdw                      0
lab_hemoglobin               0
dtype: int64

把training output加進training data的dataframe

In [11]:
data = pd.concat([training_data, training_output], axis=1)
data = data.T.drop_duplicates().T
data

#data.shape[0]
# 1834
#data.shape[1]
# 49

      PATIENT ID   age  sex  ...  lab_rdw  lab_hemoglobin  hospital_outcome
0         1478.0  72.0  1.0  ...     13.0            13.8               0.0
1           94.0  50.0  0.0  ...     13.9            13.1               0.0
2         2511.0  78.0  0.0  ...     12.9            13.9               0.0
3         1931.0  50.0  1.0  ...     13.3            14.7               0.0
4         2070.0  38.0  1.0  ...     10.6            13.4               0.0
...          ...   ...  ...  ...      ...             ...               ...
1829      2086.0  53.0  1.0  ...     11.4            15.0               0.0
1830      1769.0  91.0  1.0  ...     12.9            13.9               1.0
1831      2250.0  87.0  0.0  ...     12.9            13.9               0.0
1832       444.0  39.0  0.0  ...     12.8            14.2               0.0
1833       961.0  61.0  1.0  ...     11.7            14.9               0.0

[1834 rows x 48 columns]

**分析資料**

In [12]:
## count correlation
import pandas as pd
data_corr = data.corr()

## corr > 0.7
cor_df1 = pd.DataFrame(columns=['attribute1','attribute2','corr_value'])
for i in range(48):
  for j in range(48):
    #if(data_corr.index[i]=='hospital_outcome'):
    if(data_corr.iloc[i,j]>0.7 and i!=j):
        df_list = [ (str(data_corr.index[i]), str(data_corr.columns[j]), str(round(data_corr.iloc[i,j],2)) )]
        dfNew=pd.DataFrame(df_list, columns = ['attribute1','attribute2','corr_value'])
        cor_df1 = cor_df1.append(dfNew,ignore_index=True)

## corr < -0.7
cor_df2 = pd.DataFrame(columns=['attribute1','attribute2','corr_value'])
for i in range(48):
  for j in range(48):
    #if(data_corr.index[i]=='hospital_outcome'):
    if(data_corr.iloc[i,j]<-0.7 and i!=j):
        df_list = [ (str(data_corr.index[i]), str(data_corr.columns[j]), str(round(data_corr.iloc[i,j],2)) )]
        dfNew=pd.DataFrame(df_list, columns = ['attribute1','attribute2','corr_value'])
        cor_df2 = cor_df2.append(dfNew,ignore_index=True)

## corr with output
cor_df3 = pd.DataFrame(columns=['attribute1','attribute2','corr_value'])
for j in range(47):
    df_list = [ (str(data_corr.index[47]), str(data_corr.columns[j]), str(round(data_corr.iloc[47,j],2)) )]
    dfNew=pd.DataFrame(df_list, columns = ['attribute1','attribute2','corr_value'])
    cor_df3 = cor_df3.append(dfNew,ignore_index=True)
cor_df3.sort_values(by=['corr_value'], ascending=False)

          attribute1                 attribute2 corr_value
1   hospital_outcome                        age       0.34
39  hospital_outcome                   lab_urea       0.32
43  hospital_outcome  lab_neutrophil_percentage       0.24
42  hospital_outcome             lab_neutrophil       0.24
34  hospital_outcome                    lab_crp       0.23
22  hospital_outcome                    lab_ldh       0.22
32  hospital_outcome             lab_creatinine       0.21
36  hospital_outcome              lab_leukocyte        0.2
35  hospital_outcome                    lab_mcv       0.17
26  hospital_outcome                lab_glucose       0.16
20  hospital_outcome              pmhx_dementia       0.15
23  hospital_outcome                 lab_sodium       0.15
45  hospital_outcome                    lab_rdw       0.15
25  hospital_outcome                 lab_ddimer       0.13
18  hospital_outcome                pmhx_stroke       0.11
13  hospital_outcome                   pmhx_ckd       0.11
30  hospital_outcome                    lab_inr       0.11
12  hospital_outcome                   pmhx_ihd       0.09
14  hospital_outcome                  pmhx_copd       0.09
9   hospital_outcome              pmhx_diabetes       0.08
16  hospital_outcome          pmhx_activecancer       0.08
33  hospital_outcome                    lab_ast       0.08
29  hospital_outcome   lab_mean_platelet_volume       0.08
27  hospital_outcome              lab_potassium       0.07
11  hospital_outcome                   pmhx_htn       0.07
2   hospital_outcome                        sex       0.07
19  hospital_outcome                   pmhx_chf       0.07
10  hospital_outcome                   pmhx_hld       0.06
28  hospital_outcome                    lab_mch       0.06
17  hospital_outcome          pmhx_chronicliver       0.05
24  hospital_outcome                    lab_alt       0.02
21  hospital_outcome                   lab_aptt       0.02
7   hospital_outcome         vitals_hr_ed_first       0.01
8   hospital_outcome       vitals_spo2_ed_first      -0.29
37  hospital_outcome  lab_lymphocyte_percentage      -0.24
38  hospital_outcome   lab_prothrombin_activity      -0.11
40  hospital_outcome                    lab_rbc      -0.09
46  hospital_outcome             lab_hemoglobin      -0.07
3   hospital_outcome               ed_diagnosis      -0.07
41  hospital_outcome               lab_platelet      -0.06
0   hospital_outcome                 PATIENT ID      -0.06
6   hospital_outcome        vitals_dbp_ed_first      -0.05
44  hospital_outcome             lab_lymphocyte      -0.05
31  hospital_outcome                    lab_hct      -0.03
5   hospital_outcome        vitals_sbp_ed_first      -0.02
15  hospital_outcome                pmhx_asthma      -0.01
4   hospital_outcome       vitals_temp_ed_first       -0.0

In [13]:
## drop high correlated data
#training_data = training_data.drop(['vitals_temp_ed_first'], axis=1)
#training_data = training_data.drop(['pmhx_chf'], axis=1)
#training_data = training_data.drop(['lab_ast'], axis=1)
#training_data = training_data.drop(['lab_mcv'], axis=1)
#training_data = training_data.drop(['lab_rbc'], axis=1)
#training_data = training_data.drop(['lab_hemoglobin'], axis=1)
#training_data = training_data.drop(['lab_neutrophil'], axis=1)

## drop low correlated data (with output)
training_data = training_data.drop(['vitals_hr_ed_first'], axis=1)
training_data = training_data.drop(['lab_aptt'], axis=1)
training_data = training_data.drop(['lab_alt'], axis=1)
training_data = training_data.drop(['pmhx_chronicliver'], axis=1)
training_data = training_data.drop(['lab_mch'], axis=1)
training_data = training_data.drop(['pmhx_hld'], axis=1)
training_data = training_data.drop(['pmhx_chf'], axis=1)
training_data = training_data.drop(['sex'], axis=1)
training_data = training_data.drop(['pmhx_htn'], axis=1)
training_data = training_data.drop(['lab_potassium'], axis=1)
training_data = training_data.drop(['lab_mean_platelet_volume'], axis=1)
training_data = training_data.drop(['lab_ast'], axis=1)
training_data = training_data.drop(['pmhx_activecancer'], axis=1)
training_data = training_data.drop(['pmhx_diabetes'], axis=1)
training_data = training_data.drop(['pmhx_ihd'], axis=1)
training_data = training_data.drop(['pmhx_copd'], axis=1)
training_data = training_data.drop(['vitals_temp_ed_first'], axis=1)
training_data = training_data.drop(['pmhx_asthma'], axis=1)
training_data = training_data.drop(['vitals_sbp_ed_first'], axis=1)
training_data = training_data.drop(['lab_hct'], axis=1)
training_data = training_data.drop(['lab_lymphocyte'], axis=1)
training_data = training_data.drop(['vitals_dbp_ed_first'], axis=1)
training_data = training_data.drop(['PATIENT ID'], axis=1)
training_data = training_data.drop(['lab_platelet'], axis=1)
training_data = training_data.drop(['ed_diagnosis'], axis=1)
training_data = training_data.drop(['lab_hemoglobin'], axis=1)
training_data = training_data.drop(['lab_rbc'], axis=1)
training_data = training_data.drop(['lab_inr'], axis=1)
training_data = training_data.drop(['pmhx_ckd'], axis=1)
training_data = training_data.drop(['pmhx_stroke'], axis=1)
training_data = training_data.drop(['lab_ddimer'], axis=1)
training_data = training_data.drop(['lab_prothrombin_activity'], axis=1)
training_data = training_data.drop(['lab_sodium'], axis=1)
training_data = training_data.drop(['pmhx_dementia'], axis=1)

切成 **training set** 和 **validation set**

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(training_data, training_output, test_size=0.2)
y_train.iloc[:,1]

463     0
903     0
1785    0
62      0
1657    0
       ..
1239    0
1500    0
699     0
235     0
3       0
Name: hospital_outcome, Length: 1467, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection  import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

model = KNeighborsClassifier(n_neighbors=5)
scores = cross_val_score(model,training_data,training_output.iloc[:,1],cv=5,scoring='f1')

print(scores)
print(scores.mean())

[0.16438356 0.26865672 0.37837838 0.25       0.22222222]
0.2567281757324693

### **Model** **Selection**

**KNN**<br>
用Grid Search找參數<br>
Cross Validation Fold = 10

In [29]:
from sklearn.neighbors import KNeighborsClassifier  
from sklearn.model_selection import GridSearchCV  
 
k_range = range(1, 31)  
weight_options = ['uniform', 'distance'] 
param_grid = {'n_neighbors':k_range,'weights':weight_options} 
print(param_grid)

knn = KNeighborsClassifier(n_neighbors=10) 
grid = GridSearchCV(estimator = knn, param_grid = param_grid, cv=10, scoring='f1')
grid.fit(training_data, training_output.iloc[:,1])

print('Best score:',grid.best_score_) 
print('Prameter:',grid.best_params_) 
print('Best model：',grid.best_estimator_)

{'n_neighbors': range(1, 31), 'weights': ['uniform', 'distance']}
Best score: 0.2852007255288146
Prameter: {'n_neighbors': 4, 'weights': 'distance'}
Best model： KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='distance')

**SVM**<br>
用Grid Search找參數<br>
Cross Validation Fold = 10

In [ ]:
from sklearn.datasets import load_iris  
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import svm
 
k_range = range(1, 50) 
weight_options = ['sigmoid']
param_grid = {'C':k_range,'kernel':weight_options}
print(param_grid)
 
clf=svm.SVC(kernel='sigmoid',C=10,gamma='scale',)
 
grid = GridSearchCV(estimator = clf, param_grid = param_grid, cv=10, scoring='f1')
grid.fit(training_data, training_output.iloc[:,1])

print('Best score:',grid.best_score_) 
print('Prameter:',grid.best_params_)
print('Best model：',grid.best_estimator_)

**Decision Tree**<br>
用Grid Search找參數<br>
Cross Validation Fold = 10

In [53]:
from sklearn import tree
from sklearn.model_selection import GridSearchCV
 
k_range = ['gini', 'entropy']
splitter = ['best', 'random']
max_features = ['auto', 'sqrt', 'log2']

param_grid = {'criterion':k_range,'splitter':splitter, 'max_features':max_features} 
print(param_grid)
 
clf = tree.DecisionTreeClassifier()
 
grid = GridSearchCV(estimator = clf, param_grid = param_grid, cv=10, scoring='f1') 
grid.fit(training_data, training_output.iloc[:,1])

print('Best score:',grid.best_score_) 
print('Prameter:',grid.best_params_) 
print('Best model：',grid.best_estimator_)

{'criterion': ['gini', 'entropy'], 'splitter': ['best', 'random'], 'max_features': ['auto', 'sqrt', 'log2']}
Best score: 0.41613239163770216
Prameter: {'criterion': 'entropy', 'max_features': 'auto', 'splitter': 'random'}
Best model： DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='random')

**XGboost**<br>
用Grid Search找參數<br>
Cross Validation Fold = 10

In [56]:
from sklearn import svm
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from xgboost.sklearn import XGBClassifier
import joblib

X_train, X_test, y_train, y_test = train_test_split(training_data, training_output, test_size=0.2)

# ANOVA SVM-C
# 1) anova filter, take 3 best ranked features
anova_filter = SelectKBest(f_regression, k=17)

# 2) XGBClassifier
clf = XGBClassifier()

anova_svm = make_pipeline(anova_filter, clf)
anova_svm.fit(X_train, y_train.iloc[:,1])
y_pred = anova_svm.predict(X_test)

joblib.dump(anova_svm, './XGBClassifier-7') 
print(f1_score(y_test.iloc[:,1], y_pred, zero_division=1))

0.5434782608695652

In [18]:
from sklearn.model_selection import GridSearchCV 
from sklearn import metrics
from xgboost.sklearn import XGBClassifier

#n_estimators = range(10, 100) 
n_estimators = range(10,20) 
max_depth = range(8,10)
param_grid = {'n_estimators':n_estimators,'max_depth':max_depth}  
print(param_grid)
 
clf = XGBClassifier(n_estimators=100, max_depth=6)
 
grid = GridSearchCV(estimator = clf, param_grid = param_grid, cv=10, scoring='f1')
grid.fit(training_data, training_output.iloc[:,1])

print('Best score:',grid.best_score_)  
print('Prameter:',grid.best_params_) 
print('Best model：',grid.best_estimator_)

{'n_estimators': range(10, 20), 'max_depth': range(8, 10)}
Best score: 0.4152880913800986
Prameter: {'max_depth': 9, 'n_estimators': 11}
Best model： XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=9,
              min_child_weight=1, missing=None, n_estimators=11, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

**Random Forest**<br>
用Grid Search找參數<br>
Cross Validation Fold = 10

In [14]:
from sklearn.model_selection import GridSearchCV 
from sklearn.ensemble import RandomForestClassifier

#n_estimators = range(10, 100) 
criterion = ['gini','entropy']  
#param_grid = {'n_estimators':n_estimators,'criterion':criterion}  
param_grid = {'criterion':criterion}  
print(param_grid)
 
clf = RandomForestClassifier(n_estimators=100,criterion='gini')

 
grid = GridSearchCV(estimator = clf, param_grid = param_grid, cv=10, scoring='f1')
grid.fit(training_data, training_output.iloc[:,1])

print('Best score:',grid.best_score_)  
print('Prameter:',grid.best_params_) 
print('Best model：',grid.best_estimator_)

{'criterion': ['gini', 'entropy']}
Best score: 0.3992468651891402
Prameter: {'criterion': 'gini'}
Best model： RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

**C-SVM**<br>
執行ANOVA挑選主要特徵，並且使用C-SVM來計算特徵的權重與預測

In [12]:
from sklearn import svm
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(training_data, training_output, test_size=0.2)

# ANOVA SVM-C
# 1) anova filter, take 3 best ranked features
anova_filter = SelectKBest(f_regression, k=15)
# 2) svm
clf = svm.SVC(kernel='linear',C=3)

anova_svm = make_pipeline(anova_filter, clf)
anova_svm.fit(X_train, y_train.iloc[:,1])
y_pred = anova_svm.predict(X_test)
f1_score(y_test.iloc[:,1], y_pred, zero_division=1)

0.4556962025316456

In [4]:
from sklearn import svm
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(training_data, training_output, test_size=0.2)

# ANOVA SVM-C
# 1) anova filter, take 3 best ranked features
anova_filter = SelectKBest(f_regression, k=15)
# 2) svm
clf = svm.SVC(kernel='linear',C=5)

anova_svm = make_pipeline(anova_filter, clf)
anova_svm.fit(X_train, y_train.iloc[:,1])
y_pred = anova_svm.predict(X_test)
f1_score(y_test.iloc[:,1], y_pred, zero_division=1)

0.4731182795698925

**Cross Validation** <br>
scores = cross_val_score(clf,training_data,training_output.iloc[:,1],cv=5,scoring='f1')<br>
https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [45]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection  import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn import svm

## kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’}, default=’rbf’

clf=svm.SVC(kernel='sigmoid',C=10,gamma='scale',)
scores = cross_val_score(clf,training_data,training_output.iloc[:,1],cv=5,scoring='f1')
print(scores)
print(scores.mean())

[0.19607843 0.19354839 0.22608696 0.17821782 0.21276596]
0.20133951084400983

### **Run the testing data** <br>
Decide to use XGBoost model

In [57]:
import pandas as pd
from sklearn import svm
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from xgboost.sklearn import XGBClassifier
import joblib
from sklearn.model_selection import GridSearchCV 
from sklearn import metrics
from xgboost.sklearn import XGBClassifier

testing_data = pd.read_csv('fixed_test.csv')

## check input data size
testing_data.shape[0]
## 1834
testing_data.shape[1]
## 48

# testing_data.isnull().sum()
# testing_data.dtypes
 
## split date and time
# testing_data[['date','time']] = testing_data['admission_datetime'].str.split(" ", 1, expand=True)
testing_data = testing_data.drop(['admission_datetime'], axis=1)

## convert string into category
testing_data = testing_data.replace('MALE', 1) 
testing_data = testing_data.replace('FEMALE', 0)

## convert string into category
testing_data = testing_data.replace('sx_breathing_difficulty', 1) 
testing_data = testing_data.replace('sx_others', 2) 
testing_data = testing_data.replace('sx_flu', 3) 
testing_data = testing_data.replace('sx_fever', 4) 
testing_data = testing_data.replace('sx_cough', 5) 

## add missing data
testing_data.vitals_temp_ed_first = testing_data.vitals_temp_ed_first.fillna(testing_data['vitals_temp_ed_first'].median())
testing_data.vitals_sbp_ed_first = testing_data.vitals_sbp_ed_first.fillna(testing_data['vitals_sbp_ed_first'].median())
testing_data.vitals_dbp_ed_first = testing_data.vitals_dbp_ed_first.fillna(testing_data['vitals_dbp_ed_first'].median())
testing_data.vitals_hr_ed_first = testing_data.vitals_hr_ed_first.fillna(testing_data['vitals_hr_ed_first'].median())
testing_data.vitals_spo2_ed_first = testing_data.vitals_spo2_ed_first.fillna(testing_data['vitals_spo2_ed_first'].median())
testing_data.pmhx_diabetes = testing_data.pmhx_diabetes.fillna(testing_data['pmhx_diabetes'].mode()[0])
testing_data.pmhx_hld = testing_data.pmhx_hld.fillna(testing_data['pmhx_hld'].mode()[0])
testing_data.pmhx_htn = testing_data.pmhx_htn.fillna(testing_data['pmhx_htn'].mode()[0])
testing_data.pmhx_ihd = testing_data.pmhx_ihd.fillna(testing_data['pmhx_ihd'].mode()[0])
testing_data.pmhx_ckd = testing_data.pmhx_ckd.fillna(testing_data['pmhx_ckd'].mode()[0])
testing_data.pmhx_copd = testing_data.pmhx_copd.fillna(testing_data['pmhx_copd'].mode()[0])
testing_data.pmhx_asthma = testing_data.pmhx_asthma.fillna(testing_data['pmhx_asthma'].mode()[0])
testing_data.pmhx_activecancer = testing_data.pmhx_activecancer.fillna(testing_data['pmhx_activecancer'].mode()[0])
testing_data.pmhx_chronicliver = testing_data.pmhx_chronicliver.fillna(testing_data['pmhx_chronicliver'].mode()[0])
testing_data.pmhx_stroke = testing_data.pmhx_stroke.fillna(testing_data['pmhx_stroke'].mode()[0])
testing_data.pmhx_chf = testing_data.pmhx_chf.fillna(testing_data['pmhx_chf'].mode()[0])
testing_data.pmhx_dementia = testing_data.pmhx_dementia.fillna(testing_data['pmhx_dementia'].mode()[0])
testing_data.lab_aptt = testing_data.lab_aptt.fillna(testing_data['lab_aptt'].median())
testing_data.lab_ldh = testing_data.lab_ldh.fillna(testing_data['lab_ldh'].median())
testing_data.lab_sodium = testing_data.lab_sodium.fillna(testing_data['lab_sodium'].median())
testing_data.lab_alt = testing_data.lab_alt.fillna(testing_data['lab_alt'].median())
testing_data.lab_ddimer = testing_data.lab_ddimer.fillna(testing_data['lab_ddimer'].median())
testing_data.lab_glucose = testing_data.lab_glucose.fillna(testing_data['lab_glucose'].median())
testing_data.lab_potassium = testing_data.lab_potassium.fillna(testing_data['lab_potassium'].median())
testing_data.lab_mch = testing_data.lab_mch.fillna(testing_data['lab_mch'].median())
testing_data.lab_mean_platelet_volume = testing_data.lab_mean_platelet_volume.fillna(testing_data['lab_mean_platelet_volume'].median())
testing_data.lab_inr = testing_data.lab_inr.fillna(testing_data['lab_inr'].median())
testing_data.lab_hct = testing_data.lab_hct.fillna(testing_data['lab_hct'].median())
testing_data.lab_creatinine = testing_data.lab_creatinine.fillna(testing_data['lab_creatinine'].median())
testing_data.lab_inr = testing_data.lab_inr.fillna(testing_data['lab_inr'].median())
testing_data.lab_ast = testing_data.lab_ast.fillna(testing_data['lab_ast'].median())
testing_data.lab_crp = testing_data.lab_crp.fillna(testing_data['lab_crp'].median())
testing_data.lab_mcv = testing_data.lab_mcv.fillna(testing_data['lab_mcv'].median())
testing_data.lab_leukocyte = testing_data.lab_leukocyte.fillna(testing_data['lab_leukocyte'].median())
testing_data.lab_lymphocyte_percentage = testing_data.lab_lymphocyte_percentage.fillna(testing_data['lab_lymphocyte_percentage'].median())
testing_data.lab_prothrombin_activity = testing_data.lab_prothrombin_activity.fillna(testing_data['lab_prothrombin_activity'].median())
testing_data.lab_urea = testing_data.lab_urea.fillna(testing_data['lab_urea'].median())
testing_data.lab_rbc = testing_data.lab_rbc.fillna(testing_data['lab_rbc'].median())
testing_data.lab_platelet = testing_data.lab_platelet.fillna(testing_data['lab_platelet'].median())
testing_data.lab_neutrophil = testing_data.lab_neutrophil.fillna(testing_data['lab_neutrophil'].median())
testing_data.lab_neutrophil_percentage = testing_data.lab_neutrophil_percentage.fillna(testing_data['lab_neutrophil_percentage'].median())
testing_data.lab_lymphocyte = testing_data.lab_lymphocyte.fillna(testing_data['lab_lymphocyte'].median())
testing_data.lab_rdw = testing_data.lab_rdw.fillna(testing_data['lab_rdw'].median())
testing_data.lab_hemoglobin = testing_data.lab_hemoglobin.fillna(testing_data['lab_hemoglobin'].median())

## make sure that there are no missing data
testing_data.isnull().sum()

PATIENT ID                   0
age                          0
sex                          0
ed_diagnosis                 0
vitals_temp_ed_first         0
vitals_sbp_ed_first          0
vitals_dbp_ed_first          0
vitals_hr_ed_first           0
vitals_spo2_ed_first         0
pmhx_diabetes                0
pmhx_hld                     0
pmhx_htn                     0
pmhx_ihd                     0
pmhx_ckd                     0
pmhx_copd                    0
pmhx_asthma                  0
pmhx_activecancer            0
pmhx_chronicliver            0
pmhx_stroke                  0
pmhx_chf                     0
pmhx_dementia                0
lab_aptt                     0
lab_ldh                      0
lab_sodium                   0
lab_alt                      0
lab_ddimer                   0
lab_glucose                  0
lab_potassium                0
lab_mch                      0
lab_mean_platelet_volume     0
lab_inr                      0
lab_hct                      0
lab_creatinine               0
lab_ast                      0
lab_crp                      0
lab_mcv                      0
lab_leukocyte                0
lab_lymphocyte_percentage    0
lab_prothrombin_activity     0
lab_urea                     0
lab_rbc                      0
lab_platelet                 0
lab_neutrophil               0
lab_neutrophil_percentage    0
lab_lymphocyte               0
lab_rdw                      0
lab_hemoglobin               0
dtype: int64

In [58]:
testing_data

     PATIENT ID  age  sex  ...  lab_lymphocyte  lab_rdw  lab_hemoglobin
0          1636   42    1  ...            0.87     12.3            15.7
1           734   79    1  ...            0.72     15.4            15.4
2          1045   86    1  ...            1.29     13.9            15.8
3          1728   84    0  ...            1.10     12.8            13.8
4          1267   88    0  ...            1.20     13.6            12.2
..          ...  ...  ...  ...             ...      ...             ...
607        1735   84    1  ...            0.51     11.5            12.3
608        1807   90    0  ...            0.69     20.1            13.6
609        1464   49    1  ...            1.10      8.3            15.5
610         595   49    0  ...            1.10     12.8            13.8
611         397   62    1  ...            0.53     14.3            12.0

[612 rows x 47 columns]

In [59]:
xgb = joblib.load('./model')
ans = xgb.predict(testing_data)
ans

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])

In [63]:
output_example = pd.read_csv('test_output_example.csv')
for i in range(612):
  output_example.iloc[i,1] = ans[i]

In [65]:
output_example.to_csv('./106070038.csv' , index=False )